### ISSUE TITLE
[Issue] We need a way for large responses to not be cut.

### ISSUE THREAD

**Issue by imgidedin** [Eisenhuth/dalamud-chatgpt#1]
Currently, if a response is too big, it will cut and deliver just part of it. Can you split it in multiple messages? Maybe save it so we can check a history for eacy copy&paste?

**Comment by Eisenhuth** [comment]
I was hoping to avoid this by limiting the `max_tokens`, but I'll look into it when I have the time.

**Comment by Eisenhuth** [comment]
should be fixed in the latest release - the response can still get cut off by the response reaching the token limit. I'll look into a better long-term solution.

![image](https://user-images.githubusercontent.com/47415874/227392134-1baf668f-250d-4003-9598-f244a5578e1d.png)
