### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skylargraves** [Eisenhuth/dalamud-chatgpt#3]
I had this working when I initially tried it out. I turned it off for a bit and finally came back to it and it's giving me a error: text is null, response code: 404 - NotFound. I assume there's a simple fix on my end I messed up? I also got a new key and input that and waited a bit to see if it started working. Did not work after a day.

**Comment by Eisenhuth** [comment]
thanks for the report, OpenAI deprecated the old endpoint that I was using (`text-davinci-003`), I replaced it with `gpt-3.5-turbo-instruct` to fix the issue.

I pushed the update and the next time you update your plugins it should get picked up.

![image](https://github.com/Eisenhuth/dalamud-chatgpt/assets/47415874/135f9916-f698-4d15-8354-df886cd77072)
