### ISSUE TITLE
Error: text is null / 401 unauthorized

### ISSUE THREAD

**Issue by Rueby** [Eisenhuth/dalamud-chatgpt#4]
Basically the title, showing additional information gives the response code : 401 - unauthorized
max tokens is 256

Did I do something wrong?

**Comment by Eisenhuth** [comment]
Error 401 indicates that there is an issue with the API key, are you sure the key you entered is correct and valid?

https://help.openai.com/en/articles/6891767-error-code-401-invalid-authentication

**Comment by Rueby** [comment]
Hmmm I deleted the old one and entered another and got 429 : too many requests? but I like only sent a short one to test

**Comment by Eisenhuth** [comment]
please try replacing the API key/restarting the game, assuming you are on the current version it should work ™️ 

if it still doesn't work I'd need either the full error or a screenshot to further narrow down what exactly the issue is on your end as I can't seem to reproduce it here
